### ISSUE TITLE
Incompatible with Atom 1.39.0-beta0

### ISSUE THREAD

**Issue by shuntaroy** [hesstobi/atom-autocomplete-latex-references#9] opened 2019-06-12 04:53 UTC
**Atom**: 1.39.0-beta0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [autocomplete-latex-references](https://github.com/hesstobi/atom-autocomplete-latex-references) package 0.3.1

### Stack Trace

Failed to activate the autocomplete-latex-references package

```
At Cannot read property '1' of null

TypeError: Cannot read property '1' of null
    at module.exports (/packages/autocomplete-latex-references/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:61:29)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:82:25)
    at /packages/autocomplete-latex-references/node_modules/promisify-node/index.js:137:23
    at Array.forEach (<anonymous>)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:132:6)
    at module.exports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:164:10)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:4:6)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:1:1)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147410)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146719)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:16)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:1)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:147410)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:146719)
    at Object.provide (/packages/autocomplete-latex-references/lib/main.coffee:64:27)
    at Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:3424754)
    at Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:3421796)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:1207616)
    at Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:1209057)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:381976)
    at activatePromise.Promise.all.then (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:380727)
```

**Comment by PRemmen** [comment] 2019-08-04 09:38
Same Problem on Windows 10, see #10 

Again: sorry for duplication! :)

**Comment by PRemmen** [comment] 2019-08-13 15:15
Error still occurs with Atom 1.40.0 x64

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Windows 10
**Thrown From**: [autocomplete-latex-references](https://github.com/hesstobi/atom-autocomplete-latex-references) package 0.3.1


### Stack Trace

Failed to activate the autocomplete-latex-references package

```
At Cannot read property '1' of null

TypeError: Cannot read property '1' of null
    at module.exports (/packages/autocomplete-latex-references/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:61:29)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:82:25)
    at /packages/autocomplete-latex-references/node_modules/promisify-node/index.js:137:23
    at Array.forEach (<anonymous>)
    at processExports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:132:6)
    at module.exports (/packages/autocomplete-latex-references/node_modules/promisify-node/index.js:164:10)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:4:6)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:1:1)
    at /packages/autocomplete-latex-references/lib/label-manager.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:146745)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:16)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:1)
    at /packages/autocomplete-latex-references/lib/reference-provider.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:146745)
    at Object.provide (/packages/autocomplete-latex-references/lib/main.coffee:64:27)
    at Package.activateServices (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:3409330)
    at Package.activateNow (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:3406372)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:1210649)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:382729)
    at activatePromise.Promise.all.then (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:381480)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-python-debugger 0.3.4 
autocomplete-latex-cite 0.3.2 
autocomplete-latex-references 0.3.1 
autocomplete-python 1.14.1 
busy-signal 2.0.1 
convert-to-utf8 0.2.4 
file-icons 2.1.34 
highlight-selected 0.16.0 
intentions 1.1.5 
language-latex 1.2.0 
language-mako 0.6.0 
language-markdown 0.37.0 
language-modelica 0.5.1 
latex 0.50.2 
latex-autocomplete 1.1.1 
linter 2.3.1 
linter-flake8 2.4.0 
linter-htmlhint 1.6.2 
linter-ui-default 1.7.1 
markdown-pdf 2.2.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
preview-inline 1.5.1 
python-black 0.7.0 
split-diff 1.6.0 
symbols-tree-view 0.14.0 
wordcount 3.1.0 
```

**Comment by ofenerci** [comment] 2019-11-08 17:13
Same error in Atom 1.41

**Comment by PRemmen** [comment] 2019-12-02 10:39
Is there any chance this gets fixed in near future, I was looking for other packages but none of them was working as good as this one! :-) @hesstobi

**Comment by hesstobi** [comment] 2019-12-11 13:13
I was unable to reproduce the error. But I updated the dependencies and released a new version. Is the package now working?

**Comment by PRemmen** [comment] 2019-12-11 13:27
@hesstobi for me this fixed the error! :-) thanks a lot

**Closed as completed** 2019-12-11 14:36 UTC
